# Generated by Django 4.2.5 on 2023-10-31 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0005_alter_persona_dni_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_presentacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiantes', models.ManyToManyField(related_name='proyectos', to='persona.estudiante')),
            ],
        ),
    ]
