# Generated by Django 4.2.5 on 2023-11-01 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=100)),
                ('tipo_movimiento', models.CharField(choices=[('presenta_PTF', 'Presentación PTF'), ('pase_a_CSTF', 'pase a la CSTF'), ('dictamen_a_CSTF', 'dictamen de la CSTF sobre el formato del PTF'), ('pase_a_TE', 'Pase al TE'), ('dictamen_TE', 'Dictamen tribunal evaluador sobre evaluación PT'), ('presenta_IF', 'Presentación borrador Informe final'), ('dictamen_Borrador', 'Dictamen tribunal evaluador sobre borrador')], default='presenta_PTF', max_length=20)),
                ('archivos_relacionados', models.FileField(blank=True, null=True, upload_to='archivos_estado/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
