# Generated by Django 4.2.5 on 2023-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[('presenta_PTF', 'Presentación PTF'), ('pase_a_CSTF', 'pase a la CSTF'), ('dictamen_a_CSTF', 'dictamen de la CSTF sobre el formato del PTF'), ('pase_a_TE', 'Pase al TE'), ('dictamen_TE', 'Dictamen tribunal evaluador sobre evaluación PT'), ('presenta_IF', 'Presentación borrador Informe final'), ('dictamen_Borrador', 'Dictamen tribunal evaluador sobre borrador')], default='presenta_PTF', max_length=20, null=True),
        ),
    ]
