# Generated by Django 4.2.5 on 2023-10-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_apellido_persona_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('apellido',)},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre_completo',
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
