# Generated by Django 4.2.5 on 2023-10-18 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_options_remove_persona_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=13, unique=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
