# Generated by Django 4.2.5 on 2023-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', 'Comisión'), ('1', 'Docente'), ('2', 'Estudiante')], max_length=10, unique=True),
        ),
    ]
